export const ArrayPets =    [
    {
        id: 1,
        name:' Belia',
        type: ' Canino',
        breed: ' Husky',
        age: 2,
        gender: ' Hembra',
        image: 'https://humanidades.com/wp-content/uploads/2017/02/perro-3-e1561679226953.jpg',
    },
    {
        id: 2,
        name: ' Sombra',
        type: ' Felino',
        breed: ' Bombay',
        age: 1,
        gender: ' Macho',
        image: 'https://media.zenfs.com/es/hola.com/921570b730be790e24a7e8795782f43e',
    },
    {
        id: 3,
        name: ' Manchas',
        type: ' Canino',
        breed: ' Dalmata',
        age: 1,
        gender: ' Hembra',
        image: 'https://t1.uc.ltmcdn.com/es/posts/8/6/1/como_adiestrar_a_un_dalmata_34168_paso_1_600.jpg',
    },
    {
        id: 4,
        name: ' Luna',
        type: ' Felino',
        breed: ' Domestico',
        age: 1,
        gender: ' Hembra',
        image: 'https://nupec.com/wp-content/uploads/2022/02/cat-watching-2021-08-26-15-42-24-utc.jpg',
    },
    {
        id: 5,
        name: ' Croqueta',
        type: ' Canino',
        breed: ' Labrador',
        age: 3,
        gender: ' Macho',
        image: 'https://blog.mascotaysalud.com/wp-content/uploads/2019/09/LABRADOR-RETRIEVER-TUMBADO.jpg',
    },
    {
        id: 6,
        name: ' Tulio',
        type: ' Canino',
        breed: ' Mestizo',
        age: 2,
        gender: ' Macho',
        image: 'https://live-mascotas-sanas-duenos-felices-blogs.cphostaccess.com/posts/easset_upload_file32027_708883_e.jpg',
    },
    {
        id: 7,
        name: ' Calvin',
        type: ' Canino',
        breed: ' Mestizo',
        age: 2,
        gender: ' Macho',
        image: 'https://static.diariofemenino.com/uploads/mascotas/nombre-perro-sin-raza.jpg',
    },
    {
        id: 8,
        name: ' Yummi',
        type: ' Felino',
        breed: ' British Shorthair',
        age: 1,
        gender: ' Hembra',
        image: 'https://cdn.royalcanin-weshare-online.io/mVbc9noBBKJuub5qA7pQ/v3/bp-lot-2-british-shorthair-color-outdoor',
    },
    {
        id: 9,
        name: ' Milky',
        type: ' Canino',
        breed: ' Mestizo',
        age: 1,
        gender: ' Macho',
        image: 'https://i.pinimg.com/736x/34/4a/4c/344a4cb9c0151759d4f79a2f0fc94270.jpg',
    },
    {
        id: 10,
        name: ' Bombón',
        type: ' Felino',
        breed: ' Angora turco',
        age: 2,
        gender: ' Hembra',
        image: 'https://nfnatcane.es/blog/wp-content/uploads/2020/02/Angora-turco-enfadado.jpg',
    },
    {
        id: 11,
        name: ' Chiwa',
        type: ' Canino',
        breed: ' Chihuahua',
        age: 1,
        gender: ' Macho',
        image: 'https://labyes.com/wp-content/uploads/2022/05/chihuahua-600x600.jpg',
    },
    {
        id: 12,
        name: ' Princesa',
        type: ' Canino',
        breed: ' American Bully',
        age: 3,
        gender: ' Hembra',
        image: 'https://www.foyel.com/archivos/5/4/pit_bull_genetica_web.gif',
    }
]

/*{
        id: 10,
        name: 'Luna',
        type: 'Dog',
        breed: 'Labrador',
        age: 2,
        gender: 'Female',
        image: 'https://cdn.forbes.com.mx/2018/04/Adiestramiento-Canino-640x360.jpg',
    },*/